import { LandData, NavItem } from './types';

export const NAV_ITEMS: NavItem[] = [
  { id: 'home', label: 'হোম' },
  { id: 'features', label: 'ফিচারসমূহ' },
  { id: 'services', label: 'সেবা' },
  { id: 'about', label: 'আমাদের সম্পর্কে' },
  { id: 'contact', label: 'যোগাযোগ' },
];

export const MOCK_LAND_DATA: LandData[] = [
  {
    id: '1',
    title: 'রাজউক ৪নং সেক্টর প্লট, পূর্বাচল, ঢাকা',
    price: '৳৪৫,০০,০০০',
    rawPrice: 4500000,
    location: 'পূর্বাচল, ঢাকা',
    size: '৫ কাঠা',
    image: 'https://picsum.photos/800/600',
    details: {
      waterDepth: '১২০ ফুট',
      hospitalDistance: '২.৫ কি.মি.',
      roadDistance: '০.৫ কি.মি.',
      gasAvailability: false,
      riskScore: 25,
      floodRisk: 15,
      quakeRisk: 35,
      droughtRisk: 10,
      historicalPrices: [45, 60, 50, 95, 75, 88],
    },
    coordinates: { lat: 23.834, lng: 90.546 },
  },
  {
    id: '2',
    title: '১০ কাঠার নিষ্কণ্টক জমি, উত্তরা সেক্টর ১৫',
    price: '৳১,২০,০০,০০০',
    rawPrice: 12000000,
    location: 'উত্তরা, ঢাকা',
    size: '১০ কাঠা',
    image: 'https://picsum.photos/800/601',
    details: {
      waterDepth: '১৮০ ফুট',
      hospitalDistance: '১.২ কি.মি.',
      roadDistance: '০ কি.মি. (মেইন রোড)',
      gasAvailability: true,
      riskScore: 10,
      floodRisk: 5,
      quakeRisk: 20,
      droughtRisk: 5,
      historicalPrices: [100, 110, 115, 125, 130, 145],
    },
    coordinates: { lat: 23.875, lng: 90.395 },
  },
  {
    id: '3',
    title: 'বসুন্ধরা আবাসিক ব্লক-ডি, দক্ষিণমুখী প্লট',
    price: '৳৮৫,০০,০০০',
    rawPrice: 8500000,
    location: 'বসুন্ধরা আর/এ, ঢাকা',
    size: '৩ কাঠা',
    image: 'https://picsum.photos/800/602',
    details: {
      waterDepth: '১৫০ ফুট',
      hospitalDistance: '৫০০ মিটার',
      roadDistance: '১০০ মিটার',
      gasAvailability: true,
      riskScore: 15,
      floodRisk: 10,
      quakeRisk: 25,
      droughtRisk: 12,
      historicalPrices: [60, 65, 70, 78, 80, 85],
    },
    coordinates: { lat: 23.815, lng: 90.430 },
  },
];

export const FEATURES = [
  { icon: 'map', title: 'ইন্টারেক্টিভ ম্যাপ', desc: 'স্যাটেলাইট ভিউ সহ জমির সঠিক অবস্থান দেখুন।' },
  { icon: 'landscape', title: 'জমি ব্যবহারের ধরণ', desc: 'আবাসিক নাকি বাণিজ্যিক, তা স্বয়ংক্রিয়ভাবে শনাক্ত করুন।' },
  { icon: 'currency_ruble', title: 'বাজার দর', desc: 'এলাকার বর্তমান বাজার মূল্য যাচাই করুন।' },
  { icon: 'trending_up', title: 'ভবিষ্যৎ পূর্বাভাস', desc: 'আগামী ৫ বছরে জমির দাম কেমন হতে পারে।' },
  { icon: 'flood', title: 'বন্যা ঝুঁকি', desc: 'ঐতিহাসিক ডাটা ব্যবহার করে বন্যার ঝুঁকি বিশ্লেষণ।' },
  { icon: 'earthquake', title: 'ভূমিকম্প ঝুঁকি', desc: 'মাটির গঠন অনুযায়ী ভূমিকম্পের ঝুঁকি নির্ণয়।' },
  { icon: 'gavel', title: 'আইনি যাচাই', desc: 'জমির দলিলের প্রাথমিক আইনি সমস্যা চিহ্নিতকরণ।' },
  { icon: 'construction', title: 'উন্নয়ন সম্ভাবনা', desc: 'ভবিষ্যতে এলাকাটি কতটা উন্নত হবে তার ধারণা।' },
  { icon: 'school', title: 'নাগরিক সুবিধা', desc: 'কাছাকাছি স্কুল, কলেজ এবং হাসপাতালের তালিকা।' },
  { icon: 'water_drop', title: 'ইউটিলিটি', desc: 'গ্যাস, পানি এবং বিদ্যুতের প্রাপ্যতা যাচাই।' },
  { icon: 'query_stats', title: 'ইনসাইট প্যানেল', desc: 'গভীর বিশ্লেষণের মাধ্যমে সঠিক সিদ্ধান্ত নিন।', span: 2 },
  { icon: 'compare_arrows', title: 'লোকেশন তুলনা', desc: 'একাধিক এলাকার মধ্যে তুলনা করে সেরাটি বেছে নিন।', span: 2 },
];
